### ISSUE TITLE
Installation problems related to `~>` in the gemspec pins.

### ISSUE THREAD

**Issue by andynu** [gregmolnar/spektr#6]
Similar to #3 this project has challenges with projects that use haml 6.x

```
Resolving dependencies...
Bundler could not find compatible versions for gem "haml":
  In snapshot (Gemfile.lock):
    haml (= 6.0.7)

  In Gemfile:
    haml (~> 6.0.0)

    spektr was resolved to 0.3.2, which depends on
      haml (~> 5.1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Broader issue of using `~>` instead of `>=` in the gemspec pins**
But more broadly, any gem dependencies that are pinned with ~> unless they absolutely have to, are going to be a problem for a lot of projects. Please consider >= pins instead. This of course opens up new problems, but at least people will be able to install and report to you issues related to newer versions, rather than getting stuck at install.

```
  spec.add_dependency 'haml', '~>5.1'
  spec.add_dependency 'parser', '~> 3.0.0'
  spec.add_dependency 'ruby_parser', '~>3.13'
  spec.add_dependency 'unparser', '~> 0.6.0'
```

**Comment by gregmolnar** [comment]
I don't love the idea if not pinning the major version of parser, because on the release of the next major one, breaking changes will break spektr probably. 
But after trying to use it in a few apps I am using for testing as a gem, I need to admit that there is no other way to make this work, so I changed it.
Thanks for the report!
